export function getRandomFallback(nickname: string): string {
  const messages = [
    `Terima kasih banyak ${nickname}, ODOS kamu luar biasa! 🙌`,
    `Keren banget ${nickname}! Aksi ODOS kamu bikin semua lebih aman 💯`,
    `Mantap ${nickname}, semangat menjaga keselamatan! 🔥`,
    `ODOS kamu berdampak besar, ${nickname}! Tetap semangat! 💪`,
    `Hebat ${nickname}, terima kasih sudah peduli dengan safety kita semua 🙏`,
    `Teruskan kontribusimu ${nickname}, tambang makin aman karena kamu! 🛡️`,
    `Salut untuk ${nickname}, ODOS kamu inspiratif banget! 👏`,
    `Top banget ${nickname}, ODOS-nya bener-bener luar biasa! 🚀`,
    `Terima kasih ${nickname}, ODOS kamu menyelamatkan banyak nyawa! ❤️`,
    `Semangat terus ya ${nickname}, kamu luar biasa hari ini! ☀️`,
    `Keren ${nickname}, semangat ODOS-nya bikin tim makin solid! 🤝`,
    `Wah ${nickname}, ODOS kamu bisa jadi teladan nih! 🏅`,
    `Kamu hebat, ${nickname}! Teruskan kontribusi positifmu! ✨`,
    `ODOS dari ${nickname} hari ini sangat membantu! 🔧`,
    `Terima kasih ${nickname}, kamu pahlawan hari ini! 🦸`,
    `Aksi kamu luar biasa ${nickname}, ODOS-nya top markotop! 🛠️`,
    `Great job ${nickname}! ODOS kamu sangat bermanfaat! 🌟`,
    `Kamu bikin tambang jadi lebih aman, ${nickname}! 🧱`,
    `Good job ${nickname}, ODOS hari ini sukses besar! 🎉`,
    `Terima kasih atas ODOS hebatmu, ${nickname}! 🔥`,
    `ODOS kamu menyentuh hati kami, ${nickname}! 💖`,
    `Semangatmu luar biasa, ${nickname}! Keep it up! 💪`,
    `Aksi ODOS kamu adalah inspirasi, ${nickname}! ✊`,
    `Hebat ${nickname}, kamu bikin perbedaan nyata! 🌍`,
    `Bravo ${nickname}, ODOS kamu luar biasa hebat! 🎖️`,
    `ODOS hari ini sangat impactful berkat ${nickname}! 💥`,
    `Respect untuk ${nickname}, kontribusimu besar! 🫡`,
    `Terima kasih ${nickname}, tambang lebih aman karenamu! 🛑`,
    `Kontribusimu sangat berarti, ${nickname}! 🙇‍♂️`,
    `ODOS kamu disambut hangat oleh tim! Makasih ${nickname}! 🥳`,
    `Keren abis ${nickname}, terus jaga semangat ODOS! 🔋`,
    `ODOS kamu membawa perubahan positif, ${nickname}! 🍀`,
    `Tingkatkan terus ODOS-mu, ${nickname}! Kami dukung! ⚙️`,
    `Semangatmu hari ini bikin suasana tambah solid, ${nickname}! 💼`,
    `Kamu bagian dari perubahan, ${nickname}. Makasih ya! 🧩`,
    `Berkat ${nickname}, ODOS makin hidup! 🔄`,
    `Makin semangat nih lihat ODOS dari ${nickname}! 🌅`,
    `Kamu bikin semua jadi lebih peduli, ${nickname}! 💡`,
    `Terima kasih ${nickname}, ODOS kamu bikin kami bangga! 🏆`,
    `Luar biasa ${nickname}, ODOS kamu on point banget! 📌`,
    `Kamu adalah inspirasi bagi tim, ${nickname}! 🔰`,
    `Semangatmu menular ke kami semua, ${nickname}! 🌟`,
    `Terima kasih ${nickname}, kontribusimu selalu ditunggu! 🗓️`,
    `ODOS dari ${nickname} menunjukkan dedikasi tinggi! 👷`,
    `Maju terus ${nickname}, semangatmu menggerakkan semua! 🏃`,
    `Keren ${nickname}, kamu bikin perbedaan nyata hari ini! 🎯`,
    `Penuh semangat dan tanggung jawab, hebat ${nickname}! 📣`,
    `Tangan dingin ${nickname} bikin ODOS makin mantap! 🧤`,
    `Energi positif kamu luar biasa, ${nickname}! 🔋`,
    `Tambang ini lebih aman karena kamu, ${nickname}! 🏗️`,
    `Terima kasih telah melangkah lebih dulu, ${nickname}! 👣`,
    `ODOS-mu jadi contoh hebat, ${nickname}! 👓`,
    `Jaga terus semangatmu, ${nickname}! Kami mendukungmu penuh! 🛠️`,
    `Satu kata: keren banget ${nickname}! 🚀`,
    `Kami sangat terbantu hari ini, makasih ${nickname}! 📊`,
    `Keren ${nickname}, hari ini ODOS kamu menyentuh banyak hati! ❤️`,
    `Niat dan aksi kamu selaras, luar biasa ${nickname}! ✨`,
    `Kamu bawa perubahan positif, ${nickname}. Terima kasih! 🔄`,
    `Terima kasih atas komitmenmu ${nickname}, ODOS hari ini sukses besar! 🎉`,
    `Hebat ${nickname}, aksi nyatamu membuktikan kepedulianmu! 🤝`,
    `Tambang ini jadi tempat yang lebih aman karena kamu, ${nickname}! 🚧`,
    `Kamu inspirasi nyata, ${nickname}! Jangan berhenti melangkah! 🏞️`,
    `Respect tinggi untuk kamu, ${nickname}! ODOS kamu luar biasa! 🫡`,
    `Kehadiran ODOS-mu berdampak besar, ${nickname}! 🧭`,
    `Semangat ODOS kamu luar biasa konsisten, ${nickname}! 🔁`,
    `Teruslah bersinar, ${nickname}! ODOS kamu bikin kami bangga! 🌟`,
    `Terima kasih telah jadi bagian solusi, ${nickname}! 💡`,
    `ODOS dari ${nickname} jadi cerita inspiratif hari ini! 📖`,
    `Kamu membuktikan bahwa satu aksi bisa berdampak luas, ${nickname}! 🌐`,
    `Hebat ${nickname}, semangatmu tak pernah padam! 🔥`,
    `Kami semua belajar dari ODOS-mu, ${nickname}! 📚`,
    `Hari ini makin positif karena kontribusimu, ${nickname}! ☀️`,
    `Top banget ${nickname}, ODOS-mu bikin perbedaan! 🔧`,
    `Tetap rendah hati dan terus beraksi, ${nickname}! 🙌`,
    `Kamu bukti nyata bahwa peduli itu keren, ${nickname}! 👊`,
    `Terima kasih sudah jadi role model hari ini, ${nickname}! 🎓`,
    `ODOS kamu menunjukkan bahwa kamu peka terhadap sekitar, ${nickname}! 👀`,
    `Kamu keren banget hari ini, ${nickname}! Keep it up! 🚨`,
    `Energi kamu bikin semangat semua tim naik, ${nickname}! ⚡`,
    `Senyum kami hari ini karena ODOS kamu, ${nickname}! 😄`,
    `Berkat ODOS kamu, kita semua merasa lebih aman. Terima kasih ${nickname}! 🛑`,
    `Kontribusi kamu berharga banget hari ini, ${nickname}! 💼`,
    `Kamu menunjukkan standar baru buat kita semua, ${nickname}! 🏁`,
    `Tidak semua orang bisa seperti kamu, ${nickname}. Keren banget! 🙏`,
    `Kamu spesial, ${nickname}. ODOS-mu luar biasa berdampak! 💥`,
    `Hari ini lebih baik karena kamu, ${nickname}! 🌄`,
    `Aksi kamu menginspirasi langkah selanjutnya, ${nickname}! 🛤️`,
    `Terima kasih telah membawa perubahan nyata, ${nickname}! 🌀`,
    `Kamu membuat perbedaan yang sangat berarti, ${nickname}! 🪄`,
    `Semangatmu adalah bahan bakar kita semua, ${nickname}! ⛽`,
    `Kamu mewarnai hari ini dengan ODOS positif, ${nickname}! 🎨`,
    `Satu ODOS dari kamu, dampaknya luar biasa, ${nickname}! 🚨`,
    `Kami semua sangat terbantu hari ini, ${nickname}. Terima kasih! 📈`,
    `Maju terus ${nickname}, ODOS-mu bukti nyata komitmen! 📍`,
    `Terima kasih telah jadi inspirasi nyata hari ini, ${nickname}! 🪧`,
    `Dengan kontribusimu, kita lebih kuat, ${nickname}! 🏋️`,
    `Kamu benar-benar luar biasa hari ini, ${nickname}. Terima kasih! 🎇`,
  ];

  const randomIndex = Math.floor(Math.random() * messages.length);
  return messages[randomIndex];
}
