
const headerMsg = `**ARLIDA AUTOMATED MESSAGE**\n\n`;
const signatureMsg = `\n\n*Generated by ARLIDA Bot\n**Automated Reconciliation of Logistics & Inventory Diesel Analysis***`;

export { headerMsg, signatureMsg}